{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "please input your username:instrument1\n",
      "please input your password:111\n",
      "[166577088]\n",
      "[166577088, 166577088]\n",
      "[166577088, 166577088, 166577088]\n",
      "size of folder doesn't change\n",
      "\"msconvert\" C:\\\\Users\\\\shary\\\\Desktop\\\\computingProject\\\\Web\\\\filefolder\\\\29617_SC_MA_GCMS_H-2-845-29011_Bio21-LC-QTOF-6545.d -o C:\\Users\\shary\\Desktop\\computingProject\\Web\\filefolder\n",
      "C:\\\\Users\\\\shary\\\\Desktop\\\\computingProject\\\\Web\\\\filefolder\\\\29617_SC_MA_GCMS_H-2-845-29011_Bio21-LC-QTOF-6545.d\n",
      "29617_SC_MA_GCMS_H-2-845-29011_Bio21-LC-QTOF-6545.mzML\n",
      "1\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-8:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\shary\\Anaconda3\\lib\\threading.py\", line 916, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\shary\\Anaconda3\\lib\\site-packages\\watchdog\\observers\\api.py\", line 199, in run\n",
      "    self.dispatch_events(self.event_queue, self.timeout)\n",
      "  File \"C:\\Users\\shary\\Anaconda3\\lib\\site-packages\\watchdog\\observers\\api.py\", line 368, in dispatch_events\n",
      "    handler.dispatch(event)\n",
      "  File \"C:\\Users\\shary\\Anaconda3\\lib\\site-packages\\watchdog\\events.py\", line 330, in dispatch\n",
      "    _method_map[event_type](event)\n",
      "  File \"<ipython-input-2-ba9e20b8dd65>\", line 169, in on_created\n",
      "    self.produceJson(mzmlName)\n",
      "  File \"<ipython-input-2-ba9e20b8dd65>\", line 80, in produceJson\n",
      "    msrun = pymzml.run.Reader(mzmlpath, obo_version = '3.71.0')\n",
      "  File \"C:\\Users\\shary\\Anaconda3\\lib\\site-packages\\pymzml-2.0.2-py3.6.egg\\pymzml\\run.py\", line 97, in __init__\n",
      "    self.info['file_object'] = self._open_file(self.info['file_name'])\n",
      "  File \"C:\\Users\\shary\\Anaconda3\\lib\\site-packages\\pymzml-2.0.2-py3.6.egg\\pymzml\\run.py\", line 171, in _open_file\n",
      "    return FileInterface(path, self.info['encoding'])\n",
      "  File \"C:\\Users\\shary\\Anaconda3\\lib\\site-packages\\pymzml-2.0.2-py3.6.egg\\pymzml\\file_interface.py\", line 28, in __init__\n",
      "    self.file_handler = self._open(path)\n",
      "  File \"C:\\Users\\shary\\Anaconda3\\lib\\site-packages\\pymzml-2.0.2-py3.6.egg\\pymzml\\file_interface.py\", line 63, in _open\n",
      "    self.encoding\n",
      "  File \"C:\\Users\\shary\\Anaconda3\\lib\\site-packages\\pymzml-2.0.2-py3.6.egg\\pymzml\\file_classes\\standardMzml.py\", line 32, in __init__\n",
      "    encoding = encoding\n",
      "  File \"C:\\Users\\shary\\Anaconda3\\lib\\codecs.py\", line 897, in open\n",
      "    file = builtins.open(filename, mode, buffering)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'C:\\\\Users\\\\shary\\\\Desktop\\\\computingProject\\\\Web\\\\filefolder\\\\29617_SC_MA_GCMS_H-2-845-29011_Bio21-LC-QTOF-6545.mzML'\n",
      "\n"
     ]
    }
   ],
   "source": [
    "#This code is used for monitoring d file and coverting to mzml file and get stats\n",
    "#use watchdog to monitor folder\n",
    "from watchdog.observers import Observer\n",
    "from watchdog.events import *\n",
    "import time\n",
    "import re\n",
    "import os\n",
    "from os.path import join, getsize\n",
    "import sys\n",
    "import numpy as np\n",
    "import pymzml\n",
    "import matplotlib.pyplot as plt\n",
    "import json\n",
    "import socket, ssl\n",
    "\n",
    "address='127.0.0.1'   \n",
    "port=300 \n",
    "       \n",
    "client = socket.socket()\n",
    "\n",
    "client = ssl.wrap_socket(client,ca_certs=\"cert.pem\",cert_reqs=ssl.CERT_REQUIRED)  \n",
    "client.connect(('127.0.0.1',300))\n",
    "\n",
    "def usernameResult():\n",
    "    while True:\n",
    "        username = input('please input your username:')\n",
    "        client.sendall(('username:' + username).encode())\n",
    "        recv_msg = client.recv(1024).decode()\n",
    "        if recv_msg == 'valid':\n",
    "            break\n",
    "        else:\n",
    "            print('Wrong username, please try again')\n",
    "            continue\n",
    "def passwordResult():\n",
    "    while True:\n",
    "        password = input('please input your password:')\n",
    "        client.sendall(('password:' + password).encode())\n",
    "        recv_msg = client.recv(1024).decode()\n",
    "        if recv_msg == 'valid':\n",
    "            break\n",
    "        else:\n",
    "            print('Wrong username, please try again')\n",
    "            continue\n",
    "        \n",
    "usernameResult()\n",
    "passwordResult()\n",
    "\n",
    "def sendFile(file):\n",
    "    #print(client.recv(1024).decode())\n",
    "    client.send('begin to send'.encode())   \n",
    "    print('Begin !')\n",
    "    print(file)\n",
    "    with open(file, 'r') as f:\n",
    "        for data in f:\n",
    "            client.send(data.encode())\n",
    "\n",
    "        client.send('finish'.encode())\n",
    "        print ('Finish !')\n",
    "class FileEventHandler(FileSystemEventHandler):\n",
    "    def __init__(self):\n",
    "        FileSystemEventHandler.__init__(self)\n",
    "     \n",
    "     #get the size of a folder   \n",
    "    def getdirsize(self,dir):\n",
    "        size=0\n",
    "        for root, dirs, files in os.walk(dir):\n",
    "            size+= sum([getsize(join(root, name)) for name in files])\n",
    "        return size\n",
    "    \n",
    "    def produceJson(self,mzmlName):\n",
    "        jfile_path=r\"C:\\Users\\shary\\Desktop\\computingProject\\Web\\filefolder\"        \n",
    "        jfile_pathname=jfile_path+\"\\\\\"+mzmlName.split('.')[0]+\".json\"\n",
    "        f=open(jfile_pathname,'a')\n",
    "        f.close\n",
    "        print(1)\n",
    "        js={}#create a empty dict for json data\n",
    "        js['file name']=mzmlName\n",
    "\t\n",
    "        mzmlpath = jfile_path+\"\\\\\"+mzmlName \n",
    "        msrun = pymzml.run.Reader(mzmlpath, obo_version = '3.71.0') \n",
    "        times = msrun['TIC'].mz\n",
    "\t\t\n",
    "        intensities = msrun['TIC'].i\n",
    "        length =  max(times) - min(times)\n",
    "        js['start time']=min(times)\n",
    "        js['end time']=max(times)\n",
    "        js['length']=length\n",
    "        js['instrument']=' '#how to get instrument???\n",
    "        \n",
    "        msrun = pymzml.run.Reader(mzmlpath, obo_version = '3.71.0')\n",
    "        eicTargets = [100, 200, 300] # user defined\n",
    "        eicTol = 0.03 # user defined\n",
    "        results = []\n",
    "        for eicTarget in eicTargets:\n",
    "            results.append( {\n",
    "                'target': eicTarget,\n",
    "                'RTs' : [], # list to hold retention times\n",
    "                'ints' :  [], # list to hold intensities\n",
    "                'lowerLimit' : eicTarget - eicTol,\n",
    "                'upperLimit' : eicTarget + eicTol\n",
    "                }\n",
    "            )\n",
    "        \n",
    "        for spectrum in msrun:\n",
    "            try:\n",
    "                time = spectrum['scan start time']\n",
    "            except:\n",
    "                break \n",
    "            if spectrum['ms level'] != 1: continue\n",
    "            mzs = np.asarray(spectrum.mz,dtype=np.float64)\n",
    "            ints = np.asarray(spectrum.i,dtype=np.float64) \n",
    "            for target in results:\n",
    "                lowerLimit = target['lowerLimit']\n",
    "                upperLimit = target['upperLimit']\n",
    "                mask = np.where( (mzs > lowerLimit) & (mzs < upperLimit) ) \n",
    "                eicInts = ints[mask]\n",
    "                target['RTs'].append(time)\n",
    "                target['ints'].append(np.sum(eicInts))\n",
    "        for target in results:\n",
    "            plt.plot(target['RTs'], target['ints'])\n",
    "        #plt.show()\n",
    "        js['EIC']=results\n",
    "        #print(js)\n",
    "        js_final=json.dumps(js)\n",
    "        #print(js_final)\n",
    "        file=open(jfile_pathname,'w')\n",
    "        file.write(js_final)\n",
    "        file.close()\n",
    "        sendFile(jfile_pathname)\n",
    "        \n",
    "            \n",
    "\n",
    "#when new files/folders come in        \n",
    "    def on_created(self, event):\n",
    "       # print \"log file %s changed!\" % event.src_path\n",
    "        s=event.src_path\n",
    "        if s.endswith('.d'):\n",
    "            convertname=s.replace(\"\\\\\",\"\\\\\\\\\")\n",
    "            size_list=[]\n",
    "            while True:\n",
    "                foldersize=self.getdirsize(s)\n",
    "                size_list.append(foldersize)\n",
    "                print (size_list)\n",
    "                \n",
    "                if len(size_list)>2:\n",
    "                    #print size_list[len(size_list)-1]\n",
    "                    #print size_list[len(size_list)-3]\n",
    "                    if size_list[len(size_list)-1]==size_list[len(size_list)-3]:                   \n",
    "                        print (\"size of folder doesn't change\")\n",
    "                        break\n",
    "                #every 5 minutes    \n",
    "                time.sleep(1)    \n",
    "                \n",
    "            #put mzml file in the file that contain this code file        \n",
    "            cmd=r'\"D:\\Protoe Wizard\\msconvert\" '+convertname+ ' -o '+r'C:\\Users\\shary\\Desktop\\computingProject\\Web\\filefolder'\n",
    "            print(cmd)\n",
    "            print(convertname)\n",
    "            os.system(cmd)\n",
    "            \n",
    "            dName=convertname.split(\"\\\\\")[len(convertname.split(\"\\\\\"))-1]\n",
    "            mzmlName=dName.replace(\".d\",\".mzML\")\n",
    "            print(mzmlName)\n",
    "            #wait for json file produced\n",
    "            time.sleep(5)\n",
    "            #when convert to mzml, produce json file\n",
    "            #self.produceJson(\"pbQC009.mzML\")#change it to mzmlName\n",
    "            self.produceJson(mzmlName)\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    observer = Observer()\n",
    "    event_handler = FileEventHandler()\n",
    "    observer.schedule(event_handler,r\"C:\\Users\\shary\\Desktop\\computingProject\\Web\\filefolder\",True)\n",
    "    observer.start()\n",
    "    try:\n",
    "        while True:\n",
    "            time.sleep(1)\n",
    "    except KeyboardInterrupt:\n",
    "        observer.stop()\n",
    "    observer.join()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
